/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.apress.radio;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bg=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int listbg=0x7f020002;
    }
    public static final class id {
        public static final int loadingStatus=0x7f050001;
        public static final int stationLayout=0x7f050002;
        public static final int textElement=0x7f050000;
    }
    public static final class layout {
        public static final int list_element=0x7f030000;
        public static final int main=0x7f030001;
        public static final int stations=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
